plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'com.gradleup.shadow' version '9.4.2'
}

base.archivesName = "${project.archives_base_name}-mc${project.minecraft_version}"
def archivesName = base.archivesName.get()
version = project.mod_version
group = project.maven_group

loom {
	accessWidenerPath = file("src/main/resources/earlyloadingscreen.accesswidener")
}

configurations {
	shadowInclude
}

repositories {
	maven { url 'https://jitpack.io' }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	shadowInclude implementation('net.bytebuddy:byte-buddy-agent:1.15.10')
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${archivesName}"}
	}
}

shadowJar {
	archiveClassifier = "all-dev"
	configurations = [ project.configurations.shadowInclude ]
	from("LICENSE") {
		rename { "${it}_${archivesName}"}
	}
	relocate "net.bytebuddy", "com.ishland.earlyloadingscreen.deps.bytebuddy"
}

task("remapShadowJar", dependsOn: shadowJar) {
	doLast {
		copy {
			from shadowJar.archiveFile
			into layout.buildDirectory.dir("libs")
			rename { shadowJar.archiveFileName.get().replaceAll("-dev\\.jar\$", ".jar") }
		}
	}
}

assemble.dependsOn(remapShadowJar)

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
