pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
    }
}

rootProject.name = "EarlyLoadingScreen"
